### PR TITLE
Bugfix: Vertical layout: Japanese text isn't rotated in fo:block-container and fo:table

### PR DESCRIPTION
**Pull request by igor-vasilev**
fixed issue https://github.com/metanorma/xmlgraphics-fop/issues/8

### CODE REVIEW

**Comment by igor-vasilev** [comment]
Fixed propagation of writingMode property throughout the context hierarchy

**Comment by ronaldtse** [comment]
Thank you @igor-vasilev , my colleague @Intelligent2013 will review and get back to you.

Specifically we need to test the JIS Z 8301 document to ensure that all nested content are "vertical-ized" properly.

**Comment by Intelligent2013** [comment]
@igor-vasilev thank you!
I confirm that this PR fixes the vertical Japanese text issue in the `fo:block-container` and `fo:table`:
image

@ronaldtse the issue with vertical text for page numbers in ToC and in the footer is another issue https://github.com/metanorma/xmlgraphics-fop/issues/10. This PR fixes only https://github.com/metanorma/xmlgraphics-fop/issues/8.

**Comment by ronaldtse** [comment]
@igor-vasilev could you please help add relevant tests / documentation so we can upstream this later? Thanks.

**Pull request merged**
